params:
  app_name: "mlops-sagemaker"
  execution_role_arn: ''
  image_ecr_url : ""
  region: 'us-east-1'
  s3_bucket_name: "vikasbucketmlflow"
  experiment_id: "0"
  run_id: ""
  model_name : "model"
